# Generated by Django 4.0.6 on 2022-07-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='lastUpdated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='city',
            name='weather',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
